services:
  web:
    build: .
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      - ConnectionStrings__myconnection=Server=db;Database=cs_project;User Id=Janek;Password=1234;TrustServerCertificate=True;Encrypt=True
  cshop:
    image: ${DOCKER_REGISTRY-}cshop
    build:
      context: Shop
      dockerfile: Dockerfile
  
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrong@Pass123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
version: '3.9'